//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonComputing_ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LeonComputingEntities : DbContext
    {
        public LeonComputingEntities()
            : base("name=LeonComputingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Asociado> Tb_Asociado { get; set; }
        public virtual DbSet<Tb_Curso> Tb_Curso { get; set; }
        public virtual DbSet<Tb_Empresa> Tb_Empresa { get; set; }
        public virtual DbSet<Tb_Especialidad> Tb_Especialidad { get; set; }
        public virtual DbSet<Tb_Evento> Tb_Evento { get; set; }
        public virtual DbSet<Tb_Expositor> Tb_Expositor { get; set; }
        public virtual DbSet<Tb_Expositor_Empresa> Tb_Expositor_Empresa { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual ObjectResult<usp_PresupuestoCuposPorMes_Result> usp_PresupuestoCuposPorMes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_PresupuestoCuposPorMes_Result>("usp_PresupuestoCuposPorMes");
        }
    
        public virtual ObjectResult<usp_ObtenerCursosPorCategoria_Result> usp_ObtenerCursosPorCategoria(string nivel_dificultad)
        {
            var nivel_dificultadParameter = nivel_dificultad != null ?
                new ObjectParameter("nivel_dificultad", nivel_dificultad) :
                new ObjectParameter("nivel_dificultad", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerCursosPorCategoria_Result>("usp_ObtenerCursosPorCategoria", nivel_dificultadParameter);
        }
    
        public virtual ObjectResult<usp_ListarCursos_Result> usp_ListarCursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCursos_Result>("usp_ListarCursos");
        }
    
        public virtual ObjectResult<usp_ListarAsociados_Result> usp_ListarAsociados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAsociados_Result>("usp_ListarAsociados");
        }
    }
}
