//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonComputing_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Asociado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Asociado()
        {
            this.Tb_Evento = new HashSet<Tb_Evento>();
        }
    
        public string cod_asociado { get; set; }
        public string ape_paterno { get; set; }
        public string ape_materno { get; set; }
        public string nombres { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fecha_ingreso { get; set; }
        public string dni { get; set; }
        public string tlf_domicilio { get; set; }
        public string tlf_celular { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fech_ult_capacitacion { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> Id_Empresa { get; set; }
        public string Id_Ubigeo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_ult_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
        public string usuario_registro { get; set; }
        public Nullable<int> estado_aso { get; set; }
    
        public virtual Tb_Empresa Tb_Empresa { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Evento> Tb_Evento { get; set; }
    }
}
