//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonComputing_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Curso()
        {
            this.Tb_Evento = new HashSet<Tb_Evento>();
        }
    
        public string cod_curso { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> horas_teoria { get; set; }
        public Nullable<int> horas_practica { get; set; }
        public string nivel_dificultad { get; set; }
        public string comentarios { get; set; }
        public Nullable<int> IdEspecialidad { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_registro { get; set; }
        public string usuario_ult_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
        public Nullable<int> estado_cur { get; set; }
    
        public virtual Tb_Especialidad Tb_Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Evento> Tb_Evento { get; set; }
    }
}
