//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonComputing_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Expositor_Empresa
    {
        public string Id_Expositor { get; set; }
        public int Id_Empresa { get; set; }
        public Nullable<System.DateTime> Fecha_inicio { get; set; }
        public Nullable<System.DateTime> Fecha_finalizacion { get; set; }
        public string Cargo { get; set; }
    
        public virtual Tb_Empresa Tb_Empresa { get; set; }
        public virtual Tb_Expositor Tb_Expositor { get; set; }
    }
}
