//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeonComputing_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Empresa()
        {
            this.Tb_Asociado = new HashSet<Tb_Asociado>();
            this.Tb_Evento = new HashSet<Tb_Evento>();
            this.Tb_Expositor_Empresa = new HashSet<Tb_Expositor_Empresa>();
        }
    
        public int Id_Empresa { get; set; }
        public string Razon_Social { get; set; }
        public string Direccion { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string UrlPagWeb { get; set; }
        public string Id_Ubigeo { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string usuario_ult_modificacion { get; set; }
        public Nullable<System.DateTime> fecha_ult_modificacion { get; set; }
        public Nullable<int> estado_emp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Asociado> Tb_Asociado { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Evento> Tb_Evento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Expositor_Empresa> Tb_Expositor_Empresa { get; set; }
    }
}
