//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyVentas_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Abastecimiento
    {
        public string Cod_prv { get; set; }
        public string Cod_pro { get; set; }
        public float Pre_Aba { get; set; }
    
        public virtual Tb_Producto Tb_Producto { get; set; }
        public virtual Tb_Proveedor Tb_Proveedor { get; set; }
    }
}
