//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyVentas_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Cliente()
        {
            this.Tb_Factura = new HashSet<Tb_Factura>();
        }
    
        public string Cod_cli { get; set; }
        public string Raz_soc_cli { get; set; }
        public string Dir_cli { get; set; }
        public string Tel_cli { get; set; }
        public string Ruc_cli { get; set; }
        public string Id_Ubigeo { get; set; }
        public int Tip_cli { get; set; }
        public string Contacto { get; set; }
        public System.DateTime Fec_reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<int> Est_cli { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Factura> Tb_Factura { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
    }
}
