//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyVentas_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_RepositorioDocumentos
    {
        public int Id { get; set; }
        public string Ruta { get; set; }
        public Nullable<System.DateTime> FecRegistro { get; set; }
        public string UsuRegistro { get; set; }
    
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
